name: Visual Regression Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    # TODO: update to workload id federation
    # for auth step
      # permissions:
      #   contents: 'read'
      #   id-token: 'write'

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: build and create the current snapshot
        run: |
          yarn bootstrap
          yarn test:e2e
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull


      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        # TODO: update to workload id federation
        # with:
          # token_format: 'access_token'
          # access_token_lifetime: '300s'
          # workload_identity_provider: ${{ secrets.GOOGLE_IDENTITY_PROVIDER }}
          # service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_FOR_REG_SUIT_CI }}

      - name: run reg
        run: |
          yarn test:vt:run
