name: Visual Regression Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: build and create the current snapshot
        run: |
          yarn bootstrap
          yarn test:e2e:with-build
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull

      # export GOOGLE_APPLICATION_CREDENTIALS (1 hour lifetime)
      # https://github.com/google-github-actions/auth/blob/736e11de4059a49cee3b8430b4341308243573e3/src/main.ts#L166-L168
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_FOR_REG_SUIT_CI }}

      - name: run reg
        run: |
          yarn test:vt:run
